### ISSUE TITLE
Extending Powershell-IR 

### ISSUE THREAD

**Issue by keepwatch** [mgreen27/Invoke-LiveResponse#12]
I just submitted a PR (#11) that collected recycle bin artifacts (although I preserved your British nomenclature, lol). I noticed you incremented the version number before, so I gave this a minor version bump.

I have a few more changes nearly ready to go:
* Collecting registry transaction log files 
* Permitting authentication using a prebuilt credential object (permitting the use of password safes or other methods for providing creds without humans typing them)

Do you want me to do minor version bumps for those as well?

And finally, I configured some VMs via Vagrant to perform compatibility tests on other PS versions. It's currently manual but better than testing in production. Are you interested in merging that, or should I keep it in my own repo?

**Comment by mgreen27** [comment]
@keepwatch I just reached out to your twitter account to continue the conversation.

I am just about to bump some changes that would make bulk collections significantly easier. I plan to roll this in by Saturday US time. Registry transactions should be covered in that change, then I was planning on adding additional artefacts aligning to the SANS "evidence of" model.

Yes please add minor version bumps. I have simply been incrementing minor adds with a .01 update, but plan on moving to version 1.0 soon (with artefact refactor).

Registry transactions should be covered with that change and essentially enable us to select a folder and recursively copy/raw copy leveraging Get-ChildItem.

WRT vagrant - i'll check out your repo and go from there. I dont see why not.

PS proper queens english is the most appropriate english :)

**Comment by keepwatch** [comment]
@mgreen27, sounds good. I just pushed the Vagrant info to a branch in my repo: https://github.com/keepwatch/Powershell-IR/tree/vagrant-testing-1

**Comment by mgreen27** [comment]
Closing this as most items have been added.
