### ISSUE TITLE
-LocalOut <path> isn't working in latest commit

### ISSUE THREAD

**Issue by keepwatch** [mgreen27/Invoke-LiveResponse#29]
When I try to perform a forensic copy (`-Evtx -LocalOut "C:\tmp\"`), I get the following message: `Error: Check UNC path and credentials. Unable to Map Y:`. 

I've not kept up with the recent changes, but it looks like the error comes from [sbPathUnc.ps1](https://github.com/mgreen27/Invoke-LiveResponse/blob/master/Content/Scriptblock/Base/sbPathUnc.ps1), which doesn't appear to have any capability to write data to the local drive. 

sbPathUnc.py is getting called because a string value of `$LocalOut` is `ne` to `$True` (see line 344 below). However, the other option of [sbLocalPath.ps1](https://github.com/mgreen27/Invoke-LiveResponse/blob/master/Content/Scriptblock/Base/sbPathLocal.ps1) appears to be connected to the `-WriteScriptBlock` switch - and won't help in this case. I'm not sure how to move forward with analysis from here. 

What's the best way to run a forensic copy over the network and write the data to the disk of the analyzed system, per the original purpose of `-LocalOut`? Thanks!

https://github.com/mgreen27/Invoke-LiveResponse/blob/73a99cea94f63c41cd8779c24edbde0ffaa2b9c8/Invoke-LiveResponse.psm1#L343-L350

**Comment by mgreen27** [comment]
Thank you for testing!

This should be working now. I moved the $LocalOut check around to re-enable your use case. I initially focused on the local LocalOut use case which was creating LiveResponse scripts quickly.
