### ISSUE TITLE
Typo in Invoke-LiveResponse.psm1 

### ISSUE THREAD

**Issue by SaimonSC2** [mgreen27/Invoke-LiveResponse#3]
There is a Typo in Invoke-LiveResponse.psm1 Line 618. 

` If(!use$SSL){`
i think this should be `If(!$useSSL){`

This results in an error while Script execution.

**Comment by mgreen27** [comment]
@SaimonSC2 thank you for that!
Fixed now.

You can tell a minor fix I ran just before posting :-)
