### ISSUE TITLE
Several errors in Invoke-LiveResponse.psm1 and sbEvtx.ps1

### ISSUE THREAD

**Issue by mnrkbys** [mgreen27/Invoke-LiveResponse#32]
I have found several errors in Invoke-LiveResponse.psm1 and sbEvtx.ps1.

[Invoke-LiveResponse.psm1]
Possibly the "-UNC" option doesn't accept "<UNC>" and "<Share>"  because the regex string is not correct at line 668.
These parameters perhaps contain the letter "-".
So, I think "\w" should be "[\w-]".

[sbEvtx.ps1]
This contains lines which aren't needed obviously.
Line 8, 18, and 27, these should be deleted.

**Comment by mgreen27** [comment]
Thank you for taking the time and pointing this out. I just fixed the sbEvtx which appears to be from github sync issue.

Can you elaborate on your usecase for the -UNC issue? Are you including "" inside the UNC? It may be easier if you send me an example of the UNC path you are attempting so I can add it to my test cases.

Matt

**Comment by mgreen27** [comment]
Here is the UNC config inside the documentation:
-Map T: -UNC "\\investigator\cases /user:investigator\LiveResponse <password>" 

My assumption is you are attempting to 
-Map T: -UNC ""\\investigator\cases folder\" /user:investigator\LiveResponse <password>" 
Is that correct?

**Comment by mnrkbys** [comment]
For example, the UNC argument below doesn't accepted:
```
-UNC "\\win10-2\LiveResponse,mydomain\admin,password"
```
Because "\\win10-2" doesn't match the regex below:
```
\\\\(\w+|\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b)\\\w+
```
So, this regex should be modified like below:
```
\\\\([\w\-\.]+|\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b)\\[\w\-\.]+
```

**Comment by mgreen27** [comment]
resolved and tested. Thank you!
