### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by eladent** [mgreen27/Invoke-LiveResponse#49]
No really an issue but the project doesn't indicate a licence, would be nice to set one, so anyone can know what he can do with it !
Thanks in advance.

**Comment by mgreen27** [comment]
@eladent noted. I thought about this before but never added one. I will take a look im more detail a bit later.

**Comment by mgreen27** [comment]
just added MIT. I think thats fairly permissive for this repo. If your interested in copying with no attribution I dont mind relicence, im more interested in the project and seeing in use :)

**Comment by eladent** [comment]
Thanks !
